[general]
afm_order = false
beta = "<none>"
block_threshold = 1e-5
broy_max_it = -1
calc_energies = false
calc_mu_method = "dichotomy"
csc = false
dc = true
dc_dmft = "<none>"
dc_type = "<none>"
enforce_off_diag = true
eta = "<none>"
fixed_mu_value = "<none>"
g0_conv_crit = -1.0
g0_mix = 1.0
g0_mix_type = "linear"
gimp_conv_crit = -1.0
gw_embedding = false
h_field = 0.0
h_field_it = 0
h_int_basis = "triqs"
h_int_type = "<no default>"
h5_save_freq = 5
J = "<none>"
jobname = "dmft_dir"
load_sigma = false
load_sigma_iter = -1
magmom = "<none>"
magnetic = false
mu_gap_gb2_threshold = "<none>"
mu_gap_occ_deviation = "<none>"
mu_initial_guess = "<none>"
mu_mix_const = 1.0
mu_mix_per_occupation_offset = 0.0
mu_update_freq = 1
n_iter_dmft = "<none>"
n_iter_dmft_first = 10
n_iter_dmft_per = 2
n_iw = 1025
n_tau = 10001
n_w = 5001
noise_level_initial_sigma = 0.0
occ_conv_crit = -1.0
path_to_sigma = "<none>"
prec_mu = 1e-4
ratio_F4_F2 = "<none>"
sampling_h5_save_freq = 5
sampling_iterations = 0
seedname = "<no default>"
set_rot = "<none>"
sigma_conv_crit = -1.0
sigma_mix = 1.0
store_solver = false
U = "<none>"
U_prime = "<none>"
w_max = "<none>"
w_range = [-10, 10]

# Keys in this section that should be passed to the triqs solver
# explicitly need to be added to the triqs_solver_params
# when initializing the solver.py class from solid_dmft
[[solver]]
type = "cthyb"
idx_impurities = "<none>"
delta_interface = false
diag_delta = false
fit_max_moment = "<none>"
fit_max_n = "<none>"
fit_max_w = "<none>"
fit_min_n = "<none>"
fit_min_w = "<none>"
imag_threshold = 1.0e-14
legendre_fit = false
length_cycle = "<no default>"
loc_n_max = "<none>"
loc_n_min = "<none>"
max_time = -1
measure_chi_insertions = 100
measure_chi = "<none>"
measure_density_matrix = false
measure_G_l = false
measure_pert_order = false
move_double = true
move_shift = false
n_cycles_tot = "<no default>"
n_l = "<none>"
n_warmup_cycles = "<no default>"
off_diag_threshold = 0.0
perform_tail_fit = false
random_seed = "<none>"

[[solver]]
type = "ctint"
idx_impurities = "<none>"
length_cycle = "<no default>"
max_time = -1
measure_pert_order = false
move_double = true
n_cycles_tot = "<no default>"
n_warmup_cycles = "<no default>"
random_seed = "<none>"

[[solver]]
type = "ctseg"
idx_impurities = "<none>"
improved_estimator = false
legendre_fit = false
length_cycle = "<no default>"
max_time = -1
measure_G_iw = false
measure_G_l = false
measure_G_tau = true
measure_pert_order = false
n_cycles_tot = "<no default>"
n_l = "<none>"
n_w_b_nn = 1025
n_warmup_cycles = "<no default>"
random_seed = "<none>"

[[solver]]
type = "hubbardI"
idx_impurities = "<none>"
legendre_fit = false
measure_density_matrix = false
measure_G_l = false
measure_G_tau = true
n_l = "<none>"

[[solver]]
type = "ftps"
idx_impurities = "<none>"
bath_fit = "<no default>"
calc_me = true
diag_delta = false
dmrg_maxm = 100
dmrg_maxmB = 100
dmrg_maxmI = 100
dmrg_maxmIB = 100
dmrg_tw = 1e-9
dt = "<no default>"
enforce_gap = "<none>"
ignore_weight = 0.0
maxm = 100
maxmB = 100
maxmI = 100
maxmIB = 100
n_bath = 0
path_to_gs = "<none>"
ph_symm = false
refine_factor = 1
state_storage = "./"
sweeps = 10
tw = 1e-9

[[solver]]
type = "hartree"
idx_impurities = "<none>"
force_real = true
method = "krylov"
one_shot = false
tol = 1e-5
with_fock = false

[dft]
dft_code = "<none>"
dft_exec = "vasp_std"
mpi_env = "default"
n_cores = "<none>"
n_iter = 4
n_iter_first = "<dft.n_iter>"
plo_cfg = "plo.cfg"
projector_type = "w90"
store_eigenvals = false
w90_exec = "wannier90.x"
w90_tolerance = 1e-6

[gw]
code = "<none>"
h5_file = "<none>"
use_rot = false
it_1e = 0
it_2e = 0

[advanced]
dc_factor = "<none>"
dc_fixed_occ = "<none>"
dc_fixed_value = "<none>"
dc_nominal = false
dc_orb_shift = "<none>"
dc_J = "<general.J>"
dc_U = "<general.U>"
map_solver_struct = "<none>"
mapped_solver_struct_degeneracies = "<none>"
pick_solver_struct = "<none>"
