[general]
afm_order = false
beta = "<no default>"
block_suppress_orbital_symm = false
block_threshold = 1.0e-5
broy_max_it = -1
calc_energies = false
calc_mu_method = "dichotomy"
cpa_x = "<none>"
cpa_zeta = "<none>"
csc = false
dc = true
dc_dmft = "<none>"
dc_type = "<none>"
dft_mu = "<none>"
diag_delta = false
enforce_off_diag = false
fixed_mu_value = "<none>"
g0_conv_crit = -1.0
g0_mix = 1.0
g0_mix_type = "linear"
gimp_conv_crit = -1.0
h_field = 0.0
h_field_it = 0
h_int_basis = "triqs"
h_int_type = "<no default>"
h5_save_freq = 5
J = "<no default>"
jobname = "dmft_dir"
load_sigma = false
load_sigma_iter = -1
loc_n_min = "<none>"
loc_n_max = "<none>"
magmom = "<none>"
magnetic = false
measure_chi_insertions = 100
measure_chi_SzSz = false
mu_gap_gb2_threshold = "<none>"
mu_gap_occ_deviation = "<none>"
mu_initial_guess = "<none>"
mu_mix_const = 1.0
mu_mix_per_occupation_offset = 0.0
mu_update_freq = 1
n_iter_dmft = "<no default>"
n_iter_dmft_first = 10
n_iter_dmft_per = 2
n_iw = 1025
n_tau = 10001
noise_level_initial_sigma = 0.0
occ_conv_crit = -1.0
path_to_sigma = "<none>"
plo_cf = "plo.cfg"
prec_mu = "<no default>"
ratio_F4_F2 = "<none>"
sampling_h5_save_freq = 5
sampling_iterations = 0
seedname = "<no default>"
set_rot = "<none>"
sigma_conv_crit = -1.0
sigma_mix = 1.0
U = "<no default>"
U_prime = "U-2J"

[[solver]]
type = "cthyb"
idx_impurities = "<none>"
store_solver = false
delta_interface = false
fit_max_moment = "<none>"
fit_max_n = "<none>"
fit_max_w = "<none>"
fit_min_n = "<none>"
fit_min_w = "<none>"
imag_threshold = 1.0e-14
legendre_fit = false
length_cycle = "<no default>"
max_time = "<none>"
measure_density_matrix = false
measure_G_l = false
measure_pert_order = false
move_double = true
move_shift = false
n_cycles_tot = "<no default>"
n_l = "<none>"
n_warmup_cycles = "<no default>"
off_diag_threshold = 0.0
perform_tail_fit = false
random_seed = "<none>"

[[solver]]
type = "ctint"
idx_impurities = "<none>"
store_solver = false
length_cycle = "<no default>"
max_time = "<none>"
measure_pert_order = false
move_double = true
n_cycles_tot = "<no default>"
n_warmup_cycles = "<no default>"
random_seed = "<none>"

[[solver]]
type = "ctseg"
idx_impurities = "<none>"
store_solver = false
improved_estimator = false
legendre_fit = false
length_cycle = "<no default>"
max_time = "<none>"
measure_G_iw = false
measure_G_l = false
measure_G_tau = true
measure_pert_order = false
n_cycles_tot = "<no default>"
n_l = "<none>"
n_warmup_cycles = "<no default>"
random_seed = "<none>"

[[solver]]
type = "hubbardI"
idx_impurities = "<none>"
store_solver = false
eta = "<no default>"
legendre_fit = false
measure_density_matrix = false
measure_G_l = false
measure_G_tau = true
n_l = "<none>"
n_w = 5001
w_range = [-10, 10]

[[solver]]
type = "ftps"
idx_impurities = "<none>"
store_solver = false
bath_fit = "<no default>"
calc_me = true
dmrg_maxm = 100
dmrg_maxmB = 100
dmrg_maxmI = 100
dmrg_maxmIB = 100
dmrg_tw = 1.0e-9
dt = "<no default>"
enforce_gap = "<none>"
eta = "<no default>"
ignore_weight = 0.0
maxm = 100
maxmB = 100
maxmI = 100
maxmIB = 100
n_bath = 0
n_w = 5001
path_to_gs = "<none>"
ph_symm = false
refine_factor = 1
state_storage = "./"
sweeps = 10
tw = 1.0e-9
w_range = [-10, 10]

[[solver]]
type = "hartree"
idx_impurities = "<none>"
store_solver = false
eta = "<no default>"
force_real = true
method = "krylov"
n_w = 5001
one_shot = false
tol = 1e-5
with_fock = false
w_range = [-10, 10]

[dft]
dft_code = "<none>"
n_cores = "<none>"
n_iter = 4
n_iter_first = "<dft.n_iter>"
dft_exec = "vasp_std"
store_eigenvals = false
mpi_env = "default"
projector_type = "w90"
w90_exec = "wannier90.x"
w90_tolerance = 1.0e-6

[advanced]
dc_factor = "<none>"
dc_fixed_occ = "<none>"
dc_fixed_value = "<none>"
dc_nominal = false
dc_J = "<general.J>"
dc_U = "<general.U>"
map_solver_struct = "<none>"
mapped_solver_struct_degeneracies = "<none>"
pick_solver_struct = "<none>"
