name: build

on:
  push:
    branches: [ unstable ]
  pull_request:
    branches: [ unstable ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-20.04, cc: gcc-10, cxx: g++-10}
          - {os: ubuntu-20.04, cc: clang-12, cxx: clang++-12}

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install ubuntu dependencies
      if: matrix.os == 'ubuntu-20.04'
      run: >
        sudo apt-get update &&
        sudo apt-get install lsb-release wget software-properties-common &&
        wget -O /tmp/llvm.sh https://apt.llvm.org/llvm.sh && sudo chmod +x /tmp/llvm.sh && sudo /tmp/llvm.sh 12 &&
        curl -L https://users.flatironinstitute.org/~ccq/triqs3/focal/public.gpg | sudo apt-key add - &&
        sudo add-apt-repository "deb https://users.flatironinstitute.org/~ccq/triqs3/focal/ /" &&
        sudo apt-get update &&
        sudo apt-get install
        clang-12
        g++-10
        gfortran
        hdf5-tools
        libblas-dev
        libboost-dev
        libclang-12-dev
        libc++-12-dev
        libc++abi-12-dev
        libfftw3-dev
        libgfortran5
        libgmp-dev
        libhdf5-dev
        liblapack-dev
        libopenmpi-dev
        openmpi-bin
        openmpi-common
        openmpi-doc
        python3-clang-12
        python3-dev
        python3-mako
        python3-matplotlib
        python3-mpi4py
        python3-numpy
        python3-pip
        python3-scipy
        python3-sphinx
        python3-nbsphinx
        triqs
        triqs_dft_tools
        triqs_cthyb
        triqs_maxent

    - name: Build & Install HubbardI
      env:
        CPLUS_INCLUDE_PATH: /usr/include/openmpi:/usr/include/hdf5/serial/:$CPLUS_INCLUDE_PATH
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: |
        git clone https://github.com/TRIQS/hubbardI hubbardI.src
        mkdir hubbardI.build && cd hubbardI.build
        cmake ../hubbardI.src -DBuild_Tests=OFF
        sudo make -j1 install VERBOSE=1
        cd ../

    - name: Build solid_dmft
      env:
        CPLUS_INCLUDE_PATH: /usr/include/openmpi:/usr/include/hdf5/serial/:$CPLUS_INCLUDE_PATH
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
        LIBRARY_PATH: /usr/local/opt/llvm/lib
      run: |
        mkdir build && cd build && cmake ..
        make -j2 || make -j1 VERBOSE=1

    - name: Test solid_dmft
      env:
        DYLD_FALLBACK_LIBRARY_PATH: /usr/local/opt/llvm/lib
      run: |
        cd build
        ctest --output-on-failure
