name: build

on:
  push:
    branches: [ unstable ]

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  CTEST_PARALLEL_LEVEL: 1
  CTEST_OUTPUT_ON_FAILURE: 1
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
  OMPI_MCA_rmaps_base_oversubscribe: "yes"

permissions: 
  contents: write

jobs:
  build:

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    container: 
      image: materialstheory/solid_dmft_ci

    steps:
      - uses: actions/checkout@v4

      - name: Build solid_dmft
        run: |
          cmake -S . -B build/ -DBuild_Documentation=ON
          cmake --build build/ --verbose

      - name: Test solid_dmft
        run: |
          cmake --build build/ --target test

      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: build/doc/html/
          single-commit: true
